service: binance-order-service

provider:
  name: aws
  runtime: java17
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize:
  timeout: 29
  environment:
    BINANCE_API_KEY: ${env:BINANCE_API_KEY}
    BINANCE_API_SECRET: ${env:BINANCE_API_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  binanceOrder:
    handler: com.blackchain.BinanceOrderHandler::handleRequest
    events:
      - http:
          path: /orders
          method: post
          cors: true
      - http:
          path: /orders
          method: get
          cors: true

  dcaOrder:
    handler: com.blackchain.DCAOrderHandler::handleRequest
    events:
      - schedule:
          rate: cron(0 6 * * ? *)  # Daily at 9:00 AM UTC
          description: "Daily DCA order to buy BTC"
          enabled: true

package:
  artifact: build/libs/${self:service}-1.0.0-all.jar

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001